### ISSUE TITLE
Request for more info on the virtual rooms

### ISSUE THREAD

**Issue by NekoAlosama** [ShanonPearce/ASH-Listening-Set#4]
I can't exactly discern the source of R18 (Small Room I) and R20 (Small Room A) to R33 (Studio B). What database(s) do these rooms come from? R32 (ASH Listening Room) is definitely directly from this project, so I also wonder how it is made and what its goals are supposed to be. I seem to be preferring it over R03 (Control Room 7).

**Comment by ShanonPearce** [comment]
All of the virtual rooms were created for this project. They were created by combining a variety of existing binaural measurements in the time domain. The direct sounds were sourced from HRIR measurements of dummy heads or head and torso simulators such as the Neumann KU100 Dummy Head from the [SADIE project.](https://www.york.ac.uk/sadie-project/database.html) The early and late reflections were created by combining reverberation data from selections of binaural rooms measurements containing similar acoustic characteristics. 

The resulting 'virtual' rooms are more generic than the measured real rooms but can be customised in terms of the HRTF applied to the direct sound and reverberation quantity. It may also be worth exploring more complex binaural room simulation methods in future to achieve more defined acoustic characteristics and higher quality results. 

R32 (ASH Listening Room) was created as an alternative to R04 (Listening Room, University of Salford). The intention was to achieve similar acoustics to R04 and include a range of source angles on both the median plane and the horizontal planes, as the existing rooms were limited to directions on the horizontal plane.

**Comment by junh1024** [comment]
Thanks Shanon for releasing the ASH listening set. Some questions:

1. I would like to make my own 7.1.4 IR. Which of the original datasets have elevation samples?
2. Since this set is under a CC BY NC SA licence, does that mean if I release music processed with these IRs, I must include a Creative Commons notice AND the music must be non commercial?

**Comment by ShanonPearce** [comment]
> 1. I would like to make my own 7.1.4 IR. Which of the original datasets have elevation samples?

I can't recall any elevation samples being available in any of the original datasets when I was preparing the BRIRs. I did find that the following BRIR dataset [bbcrd-brirs](https://github.com/bbc/bbcrd-brirs) contains elevation samples however I haven't integrated this one into my dataset.
> 2. Since this set is under a CC BY NC SA licence, does that mean if I release music processed with these IRs, I must include a Creative Commons notice AND the music must be non commercial?

I don't have any issue with using any of the data provided in the ASH Listening Set dataset to produce music for commercial purposes.

**Comment by NekoAlosama** [comment]
Closing since the ASH-Toolset was released.
